In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [29]:
# data collection an sorting
data = pd.read_csv("../../data/titanic/titanic.csv")
data.shape
data.columns
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:

features = ['Fare', 'Pclass', 'Sex', 'Age']
x = data[features]
y = data['Survived']
y
x['Sex'] = x['Sex'].map({'female': 0, 'male': 1})

In [31]:
# splitting data into Train, Validation, Test

x_train,x_temp,y_train,y_temp = train_test_split(
    x,
    y,
    test_size = 0.25,
    random_state=42
)

# splitting temp i.e testing datat into validation and testing data
x_val, x_test, y_val, y_test = train_test_split(
    x_temp,
    y_temp,
    test_size=0.5,
    random_state=42
)
x_train

         Fare  Pclass  Sex    Age
298   30.5000       1    1    NaN
884    7.0500       3    1  25.00
247   14.5000       2    0  24.00
478    7.5208       3    1  22.00
305  151.5500       1    1   0.92
..        ...     ...  ...    ...
106    7.6500       3    0  21.00
270   31.0000       1    1    NaN
860   14.1083       3    1  41.00
435  120.0000       1    0  14.00
102   77.2875       1    1  21.00

[668 rows x 4 columns]

In [32]:
# cleaning handling msising values
train_median = x_train["Age"].median() #to prevent data leakage not req at this level but useful
x_train['Age'] = x_train['Age'].fillna(train_median)
x_val['Age'] = x_val['Age'].fillna(train_median)
x_test['Age'] = x_test['Age'].fillna(train_median)
x_train

         Fare  Pclass  Sex    Age
298   30.5000       1    1  28.00
884    7.0500       3    1  25.00
247   14.5000       2    0  24.00
478    7.5208       3    1  22.00
305  151.5500       1    1   0.92
..        ...     ...  ...    ...
106    7.6500       3    0  21.00
270   31.0000       1    1  28.00
860   14.1083       3    1  41.00
435  120.0000       1    0  14.00
102   77.2875       1    1  21.00

[668 rows x 4 columns]

In [33]:
# kyu kar re hai nai malum waps gpt mar le
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_val = scaler.transform(x_val)

x_test = scaler.transform(x_test)
x_train

array([[-0.0325683 , -1.62051704,  0.72224656, -0.08764782],
       [-0.48733085,  0.80934914,  0.72224656, -0.31820308],
       [-0.34285405, -0.40558395, -1.38456873, -0.39505484],
       ...,
       [-0.35045024,  0.80934914,  0.72224656,  0.91142501],
       [ 1.7030926 , -1.62051704, -1.38456873, -1.1635724 ],
       [ 0.8747751 , -1.62051704,  0.72224656, -0.62561011]],
      shape=(668, 4))

In [34]:
# model 1 - Logistic Regression
Lmodel = LogisticRegression()
Lmodel.fit(x_train, y_train)
lreg_score = Lmodel.score(x_val, y_val)
lreg_score

0.8108108108108109

In [35]:
# Model 2 - randomforest
rmodel = RandomForestClassifier()
rmodel.fit(x_train, y_train)
rand_score = rmodel.score(x_val,y_val)
rand_score

0.8288288288288288

In [36]:
# Model 3 - gradientboosting
gradmodel = GradientBoostingClassifier()
gradmodel.fit(x_train, y_train)
grad_score = gradmodel.score(x_val,y_val)
grad_score

0.8378378378378378

In [37]:
gradmodel.score(x_test,y_test)

0.8035714285714286